//
// BlockedDomainAttemptCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BlockedDomainAttemptCreate: Codable, JSONEncodable, Hashable {

    public var deviceName: String?
    public var domainName: String
    public var label: String?
    public var timestamp: Date?

    public init(deviceName: String? = nil, domainName: String, label: String? = nil, timestamp: Date? = nil) {
        self.deviceName = deviceName
        self.domainName = domainName
        self.label = label
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceName = "device_name"
        case domainName = "domain_name"
        case label
        case timestamp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceName, forKey: .deviceName)
        try container.encode(domainName, forKey: .domainName)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
    }
}

