//
// CompanionsPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompanionsPublic: Codable, JSONEncodable, Hashable {

    public var count: Int
    public var data: [CompanionPublic]

    public init(count: Int, data: [CompanionPublic]) {
        self.count = count
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(data, forKey: .data)
    }
}

