//
// JournalPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JournalPublic: Codable, JSONEncodable, Hashable {

    public var count: Int
    public var data: [JournalEntryPublic]

    public init(count: Int, data: [JournalEntryPublic]) {
        self.count = count
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(data, forKey: .data)
    }
}

