//
// StripeCustomer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StripeCustomer: Codable, JSONEncodable, Hashable {

    public var customer: AnyCodable

    public init(customer: AnyCodable) {
        self.customer = customer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customer, forKey: .customer)
    }
}

