//
// UserUpdateMe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserUpdateMe: Codable, JSONEncodable, Hashable {

    public var fullName: String?
    public var email: String?

    public init(fullName: String? = nil, email: String? = nil) {
        self.fullName = fullName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullName = "full_name"
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

