//
// CheckoutSessionEmbedded.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CheckoutSessionEmbedded: Codable, JSONEncodable, Hashable {

    public var clientSecret: String

    public init(clientSecret: String) {
        self.clientSecret = clientSecret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientSecret = "client_secret"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientSecret, forKey: .clientSecret)
    }
}

