//
// HabitsPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HabitsPublic: Codable, JSONEncodable, Hashable {

    public var data: [HabitPublic]
    public var count: Int

    public init(data: [HabitPublic], count: Int) {
        self.data = data
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(count, forKey: .count)
    }
}

