//
// ReportPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReportPublic: Codable, JSONEncodable, Hashable {

    public var email: String
    public var fullName: String
    public var createdAt: Date?
    public var relapses: [RelapseReport]
    public var blockedDomainAttempts: [BlockedDomainAttemptReport]

    public init(email: String, fullName: String, createdAt: Date? = nil, relapses: [RelapseReport], blockedDomainAttempts: [BlockedDomainAttemptReport]) {
        self.email = email
        self.fullName = fullName
        self.createdAt = createdAt
        self.relapses = relapses
        self.blockedDomainAttempts = blockedDomainAttempts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case fullName = "full_name"
        case createdAt = "created_at"
        case relapses
        case blockedDomainAttempts = "blocked_domain_attempts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(fullName, forKey: .fullName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(relapses, forKey: .relapses)
        try container.encode(blockedDomainAttempts, forKey: .blockedDomainAttempts)
    }
}

