//
// UpdateSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateSubscription: Codable, JSONEncodable, Hashable {

    public var stripeSubscriptionId: String?
    public var stripeProductId: String?
    public var planName: String?
    public var subscriptionStatus: String?

    public init(stripeSubscriptionId: String? = nil, stripeProductId: String? = nil, planName: String? = nil, subscriptionStatus: String? = nil) {
        self.stripeSubscriptionId = stripeSubscriptionId
        self.stripeProductId = stripeProductId
        self.planName = planName
        self.subscriptionStatus = subscriptionStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stripeSubscriptionId = "stripe_subscription_id"
        case stripeProductId = "stripe_product_id"
        case planName = "plan_name"
        case subscriptionStatus = "subscription_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(stripeSubscriptionId, forKey: .stripeSubscriptionId)
        try container.encodeIfPresent(stripeProductId, forKey: .stripeProductId)
        try container.encodeIfPresent(planName, forKey: .planName)
        try container.encodeIfPresent(subscriptionStatus, forKey: .subscriptionStatus)
    }
}

