//
// LoginAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class LoginAPI {

    /**
     Login Access Token
     
     - parameter password: (form)  
     - parameter username: (form)  
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter scope: (form)  (optional, default to "")
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loginLoginAccessToken(password: String, username: String, clientId: String? = nil, clientSecret: String? = nil, grantType: String? = nil, scope: String? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Token?, _ error: Error?) -> Void)) -> RequestTask {
        return loginLoginAccessTokenWithRequestBuilder(password: password, username: username, clientId: clientId, clientSecret: clientSecret, grantType: grantType, scope: scope).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Login Access Token
     - POST /api/v1/login/access-token
     - OAuth2 compatible token login, get an access token for future requests
     - parameter password: (form)  
     - parameter username: (form)  
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter scope: (form)  (optional, default to "")
     - returns: RequestBuilder<Token> 
     */
    open class func loginLoginAccessTokenWithRequestBuilder(password: String, username: String, clientId: String? = nil, clientSecret: String? = nil, grantType: String? = nil, scope: String? = nil) -> RequestBuilder<Token> {
        let localVariablePath = "/api/v1/login/access-token"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "client_id": clientId?.encodeToJSON(),
            "client_secret": clientSecret?.encodeToJSON(),
            "grant_type": grantType?.encodeToJSON(),
            "password": password.encodeToJSON(),
            "scope": scope?.encodeToJSON(),
            "username": username.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/x-www-form-urlencoded",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Token>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Refresh Token
     
     - parameter refreshToken: (query)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loginRefreshToken(refreshToken: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: Token?, _ error: Error?) -> Void)) -> RequestTask {
        return loginRefreshTokenWithRequestBuilder(refreshToken: refreshToken).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Refresh Token
     - POST /api/v1/login/refresh-token
     - Refresh an access token using a refresh token
     - parameter refreshToken: (query)  
     - returns: RequestBuilder<Token> 
     */
    open class func loginRefreshTokenWithRequestBuilder(refreshToken: String) -> RequestBuilder<Token> {
        let localVariablePath = "/api/v1/login/refresh-token"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "refresh_token": (wrappedValue: refreshToken.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Token>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Test Token
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func loginTestToken(apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserPublic?, _ error: Error?) -> Void)) -> RequestTask {
        return loginTestTokenWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Test Token
     - POST /api/v1/login/test-token
     - Test access token
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - returns: RequestBuilder<UserPublic> 
     */
    open class func loginTestTokenWithRequestBuilder() -> RequestBuilder<UserPublic> {
        let localVariablePath = "/api/v1/login/test-token"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserPublic>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
