//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SystemAPI {

    /**
     Create Blocked Request Attempt
     
     - parameter blockedDomainAttemptServer: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func systemCreateBlockedRequestAttempt(blockedDomainAttemptServer: BlockedDomainAttemptServer, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: AnyCodable?, _ error: Error?) -> Void)) -> RequestTask {
        return systemCreateBlockedRequestAttemptWithRequestBuilder(blockedDomainAttemptServer: blockedDomainAttemptServer).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Blocked Request Attempt
     - POST /api/v1/system/blocked-request
     - Create a blocked request attempt. This endpoint can only be accessed with a valid DNS API key.
     - API Key:
       - type: apiKey Apollo-DNS-API-Key (HEADER)
       - name: DNS_API_Key
     - parameter blockedDomainAttemptServer: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func systemCreateBlockedRequestAttemptWithRequestBuilder(blockedDomainAttemptServer: BlockedDomainAttemptServer) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/system/blocked-request"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: blockedDomainAttemptServer)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
