//
// BlockedDomainAttemptCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BlockedDomainAttemptCreate: Sendable, Codable, JSONEncodable, Hashable {

    public var domainName: String
    public var timestamp: Date?
    public var label: String?
    public var deviceName: String?

    public init(domainName: String, timestamp: Date? = nil, label: String? = nil, deviceName: String? = nil) {
        self.domainName = domainName
        self.timestamp = timestamp
        self.label = label
        self.deviceName = deviceName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainName = "domain_name"
        case timestamp
        case label
        case deviceName = "device_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domainName, forKey: .domainName)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(deviceName, forKey: .deviceName)
    }
}

