//
// BlockedDomainAttemptServer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BlockedDomainAttemptServer: Sendable, Codable, JSONEncodable, Hashable {

    public var ip: String
    public var domain: String
    public var timeStamp: Date?

    public init(ip: String, domain: String, timeStamp: Date? = nil) {
        self.ip = ip
        self.domain = domain
        self.timeStamp = timeStamp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ip
        case domain
        case timeStamp = "time_stamp"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ip, forKey: .ip)
        try container.encode(domain, forKey: .domain)
        try container.encodeIfPresent(timeStamp, forKey: .timeStamp)
    }
}

