//
// DevicePublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DevicePublic: Sendable, Codable, JSONEncodable, Hashable {

    public var allowedIps: String
    public var id: UUID
    public var ipAddress: String
    public var name: String
    public var privateKey: String
    public var serverId: UUID
    public var userId: UUID

    public init(allowedIps: String, id: UUID, ipAddress: String, name: String, privateKey: String, serverId: UUID, userId: UUID) {
        self.allowedIps = allowedIps
        self.id = id
        self.ipAddress = ipAddress
        self.name = name
        self.privateKey = privateKey
        self.serverId = serverId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowedIps = "allowed_ips"
        case id
        case ipAddress = "ip_address"
        case name
        case privateKey = "private_key"
        case serverId = "server_id"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowedIps, forKey: .allowedIps)
        try container.encode(id, forKey: .id)
        try container.encode(ipAddress, forKey: .ipAddress)
        try container.encode(name, forKey: .name)
        try container.encode(privateKey, forKey: .privateKey)
        try container.encode(serverId, forKey: .serverId)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DevicePublic: Identifiable {}
