//
// HabitCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HabitCreate: Sendable, Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var lastCompleted: Date?
    public var title: String

    public init(lastCompleted: Date?, title: String) {
        self.lastCompleted = lastCompleted
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lastCompleted = "last_completed"
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lastCompleted, forKey: .lastCompleted)
        try container.encode(title, forKey: .title)
    }
}

