//
// JournalEntryPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JournalEntryPublic: Sendable, Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var title: String
    public var hashedEntry: String
    public var lastModified: Date?
    public var id: UUID
    public var userId: UUID

    public init(title: String, hashedEntry: String, lastModified: Date? = nil, id: UUID, userId: UUID) {
        self.title = title
        self.hashedEntry = hashedEntry
        self.lastModified = lastModified
        self.id = id
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case hashedEntry = "hashed_entry"
        case lastModified = "last_modified"
        case id
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(hashedEntry, forKey: .hashedEntry)
        try container.encodeIfPresent(lastModified, forKey: .lastModified)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension JournalEntryPublic: Identifiable {}
