//
// JournalEntryUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JournalEntryUpdate: Sendable, Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var hashedEntry: String?
    public var lastModified: Date?
    public var title: String?

    public init(hashedEntry: String? = nil, lastModified: Date?, title: String? = nil) {
        self.hashedEntry = hashedEntry
        self.lastModified = lastModified
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hashedEntry = "hashed_entry"
        case lastModified = "last_modified"
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hashedEntry, forKey: .hashedEntry)
        try container.encode(lastModified, forKey: .lastModified)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

