//
// RelapsePublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RelapsePublic: Sendable, Codable, JSONEncodable, Hashable {

    public var timestamp: Date?
    public var id: UUID
    public var userId: UUID

    public init(timestamp: Date? = nil, id: UUID, userId: UUID) {
        self.timestamp = timestamp
        self.id = id
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case id
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RelapsePublic: Identifiable {}
