//
// ReportPublic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReportPublic: Sendable, Codable, JSONEncodable, Hashable {

    public var blockedDomainAttempts: [BlockedDomainAttemptReport]
    public var createdAt: Date?
    public var email: String
    public var fullName: String
    public var relapses: [RelapseReport]

    public init(blockedDomainAttempts: [BlockedDomainAttemptReport], createdAt: Date? = nil, email: String, fullName: String, relapses: [RelapseReport]) {
        self.blockedDomainAttempts = blockedDomainAttempts
        self.createdAt = createdAt
        self.email = email
        self.fullName = fullName
        self.relapses = relapses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockedDomainAttempts = "blocked_domain_attempts"
        case createdAt = "created_at"
        case email
        case fullName = "full_name"
        case relapses
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(blockedDomainAttempts, forKey: .blockedDomainAttempts)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(email, forKey: .email)
        try container.encode(fullName, forKey: .fullName)
        try container.encode(relapses, forKey: .relapses)
    }
}

