//
// UserUpdateMe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserUpdateMe: Sendable, Codable, JSONEncodable, Hashable {

    public var email: String?
    public var fullName: String?

    public init(email: String? = nil, fullName: String? = nil) {
        self.email = email
        self.fullName = fullName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case fullName = "full_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(fullName, forKey: .fullName)
    }
}

