//
// BlockedDomainAttemptsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class BlockedDomainAttemptsAPI {

    /**
     Create Blocked Domain Attempt
     
     - parameter blockedDomainAttemptCreate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BlockedDomainAttemptPublic
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockedDomainAttemptsCreateBlockedDomainAttempt(blockedDomainAttemptCreate: BlockedDomainAttemptCreate, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> BlockedDomainAttemptPublic {
        return try await blockedDomainAttemptsCreateBlockedDomainAttemptWithRequestBuilder(blockedDomainAttemptCreate: blockedDomainAttemptCreate, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create Blocked Domain Attempt
     - POST /api/v1/blocked-domain-attempts/
     - Create a new blocked domain attempt.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter blockedDomainAttemptCreate: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BlockedDomainAttemptPublic> 
     */
    open class func blockedDomainAttemptsCreateBlockedDomainAttemptWithRequestBuilder(blockedDomainAttemptCreate: BlockedDomainAttemptCreate, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<BlockedDomainAttemptPublic> {
        let localVariablePath = "/api/v1/blocked-domain-attempts/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: blockedDomainAttemptCreate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BlockedDomainAttemptPublic>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete Blocked Domain Attempt
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BlockedDomainAttemptPublic
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockedDomainAttemptsDeleteBlockedDomainAttempt(id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> BlockedDomainAttemptPublic {
        return try await blockedDomainAttemptsDeleteBlockedDomainAttemptWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete Blocked Domain Attempt
     - DELETE /api/v1/blocked-domain-attempts/{id}
     - Delete a blocked domain attempt.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BlockedDomainAttemptPublic> 
     */
    open class func blockedDomainAttemptsDeleteBlockedDomainAttemptWithRequestBuilder(id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<BlockedDomainAttemptPublic> {
        var localVariablePath = "/api/v1/blocked-domain-attempts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BlockedDomainAttemptPublic>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Read Blocked Domain Attempt
     
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BlockedDomainAttemptPublic
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockedDomainAttemptsReadBlockedDomainAttempt(id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> BlockedDomainAttemptPublic {
        return try await blockedDomainAttemptsReadBlockedDomainAttemptWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Read Blocked Domain Attempt
     - GET /api/v1/blocked-domain-attempts/{id}
     - Get blocked domain attempt by ID.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BlockedDomainAttemptPublic> 
     */
    open class func blockedDomainAttemptsReadBlockedDomainAttemptWithRequestBuilder(id: UUID, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<BlockedDomainAttemptPublic> {
        var localVariablePath = "/api/v1/blocked-domain-attempts/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BlockedDomainAttemptPublic>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Read Blocked Domain Attempts
     
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: BlockedDomainAttemptsPublic
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func blockedDomainAttemptsReadBlockedDomainAttempts(skip: Int? = nil, limit: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> BlockedDomainAttemptsPublic {
        return try await blockedDomainAttemptsReadBlockedDomainAttemptsWithRequestBuilder(skip: skip, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Read Blocked Domain Attempts
     - GET /api/v1/blocked-domain-attempts/
     - Retrieve blocked domain attempts.
     - OAuth:
       - type: oauth2
       - name: OAuth2PasswordBearer
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<BlockedDomainAttemptsPublic> 
     */
    open class func blockedDomainAttemptsReadBlockedDomainAttemptsWithRequestBuilder(skip: Int? = nil, limit: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<BlockedDomainAttemptsPublic> {
        let localVariablePath = "/api/v1/blocked-domain-attempts/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "skip": (wrappedValue: skip?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BlockedDomainAttemptsPublic>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
